DirectoryPath: "public"
#CheckExternal: false # Returned to default, use flag on GH action, default true in dev env
IgnoreURLs:
  # dev server
  - livereload
  # old article links
  - smileville\.co\.uk
  - merc-inc\.co\.uk
  - www\.microsoft\.com\/windows\/windows-7
  - forums\.beyondunreal\.com\/showthread\.php\?t=182976
  - www\.shephardsmind\.half-lifecreations\.com
  - www\.s2games\.com
  - weechat\.flashtux\.org
  - fav\.me\/d4hzu39
  - labs\.bittorrent\.com\/bleep
  - opengarden\.com\/firechat
  - appear\.in
